sudo: false
language: go
services:
  - redis-server
go:
  - 1.5
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
